#include "FunctionHelper.h"

// Exec
std::map<std::string, std::map<short, std::string>> FunctionHelper::library_helper_ = {

   { "default", {
      { -6, "Open"},
      { -12, "Close"},
      { -18, "Expunge"},
      { -24, "ExtFunc"},
      }
   },
   { "exec.library", {
      { -480 , "AbortIO" },
      { -432 , "AddDevice"},
      { -240 , "AddHead"},
      { -168 , "AddIntServer" },
      { -396 , "AddLibrary"},
      { -618 , "AddMemList"},
      { -354 , "AddPort"},
      { -486 , "AddResouree"},
      { -600 , "AddSemaphore"},
      { -246 , "AddTail"},
      { -282 , "AddTask"},
      { -108 , "Alert"},
      { -204 , "AllocAbs"},
      { -186 , "Allocate"},
      { -222 , "AllocEntry"},
      { -198 , "AllocMem"},
      { -330 , "AllocSignal"},
      { -342 , "AllocTrap"},
      { -576 , "AttemptSemaphore"},
      { -216 , "AvailMem"},
      { -180 , "Cause"},
      { -366 , "CBump"},
      { -468 , "CheckIO"},
      { -450 , "CloseDevice"},
      { -414 , "CloseLibrary"},
      { -624 , "CopyMem"},
      { -630 , "CopyMemQuick"},
      { -192 , "Deallocate"},
      { -114 , "Debug"},
      { -120 , "Disable"},
      { -465 , "DoIO"},
      { -126 , "Enable"},
      { -270 , "Enqueue"},
      { -276 , "FindName"},
      { -390 , "FindPort"},
      { -96  , "FindResident"},
      { -612 , "FindSemaphore"},
      { -294 , "FindTask"},
      { -132 , "Forbid"},
      { -228 , "FreeEntry"},
      { -210 , "FreeMem"},
      { -336 , "FreeSignal"},
      { -348 , "FreeTrap"},
      { -528 , "GetCC"},
      { -372 , "GetMsg"},
      { -72  , "InitCode"},
      { -102 , "InitResident"},
      { -78  , "InitStruct"},
      { -234 , "Insert"},
      { -90  , "MakeFunctions"},
      { -84  , "MakeLibrary"},
      { -564 , "ObtainSemaphore"},
      { -582 , "ObtainSemaphoreLi"},
      { -408 , "OldOpenLibrary"},
      { -444 , "OpenDevice"},
      { -552 , "OpenLibrary"},
      { -498 , "OpenResource"},
      { -138 , "Permit"},
      { -540 , "Procure"},
      { -366 , "PutMsg"},
      { -522 , "RawDoFmt"},
      { -570 , "ReleaseSemaphore"},
      { -588 , "ReleaseSemaphoreL"},
      { -438 , "RemDevice"},
      { -258 , "RemHead"},
      { -174 , "RemIntServer"},
      { -402 , "RemLibrary"},
      { -252 , "Remove"},
      { -360 , "RemPort"},
      { -492 , "RemResource"},
      { -606 , "RemSemaphore"},
      { -264 , "RemTail"},
      { -288 , "RemTask"},
      { -378 , "ReplyMsg"},
      { -462 , "SendIO"},
      { -312 , "SetExcept"},
      { -420 , "SetFunction"},
      { -162 , "SetIntVector"},
      { -306 , "SetSignal"},
      { -144 , "SetSR"},
      { -300 , "SetTaskPri"},
      { -324 , "Signal"},
      { -612 , "SumKickData"},
      { -426 , "SumLibrary"},
      { -150 , "SuperState"},
      { -534 , "TypeOfMem"},
      { -156 , "UserState"},
      { -546 , "Vacate"},
      { -318 , "Wait"},
      { -474 , "WaitIO"},
      { -384 , "WaitPort"},
      }
   },
   { "diskfont.library", {
      { -36 , "AvailFonts"},
      { -48 , "DisposeFontContents"},
      { -42 , "NewFontContents"},
      { -30 , "OpenDiskFont"},
      }
   },
   { "dos.library", {
      { -36 , "Close"},
      { -120 , "CreateDir"},
      { -138 , "CreateProc"},
      { -126 , "CurrentDir"},
      { -192 , "DateStamp"},
      { -198 , "Delay"},
      { -72 , "DeleteFile"},
      { -174 , "DeviceProc"},
      { -96 , "Duplock"},
      { -102 , "Examine"},
      { -222 , "Execute"},
      { -144 , "Exit"},
      { -108 , "ExNext"},
      { -114 , "Info"},
      { -54 , "Input"},
      { -132 , "IoErr"},
      { -216 , "IsInteractive"},
      { -150 , "LoadSeg"},
      { -84  , "Lock"},
      { -30  , "Open"},
      { -60  , "Output"},
      { -210 , "ParentDir"},
      { -42  , "Read"},
      { -78  , "Rename"},
      { -66  , "Seek"},
      { -180 , "SetComment"},
      { -186 , "SetProtection"},
      { -156 , "UnLoadSeg"},
      { -90  , "UnLock"},
      { -204 , "WaitForChar"},
      { -48  , "Write"},
      }
   },
   { "expansion.library", {
      { -30, "AddConfigDev"},
      { -150, "AddDosNode"},
      { -42, "AllocBoardMem"},
      { -48, "AllocConfigDev"},
      { -54, "AllocExpansionMem"},
      { -60, "ConfigBoard"},
      { -66, "ConfigChain"},
      { -72, "FindConfigBoard"},
      { -78, "FreeBoardMem"},
      { -84, "FreeConfigDev"},
      { -90, "FreeExpansionMem"},
      { -138, "GetCurrentBinding"},
      { -144, "MakeDosNode"},
      { -120, "ObtainConfigBinding "},
      { -96, "ReadExpansionByte"},
      { -102, "ReadExpansionRom"},
      { -126, "ReleaseConfigBinding"},
      { -108, "RemConfigDev"},
      { -132, "SetCurrentBinding"},
      { -114, "WriteExpansionByte"},
      }
   },
   {  "graphics.library", {
      { -156 , "AddAnimOb"},
      { -96, "AddBob"},
      { -480, "AddFont"},
      { -102, "AddVSprite"},
      { -492, "AllocRaster"},
      { -504, "AndRectRegion"},
      { -624, "AndRegionRegion"},
      { -162, "Animate"},
      { -258, "AreaDraw"},
      { -186, "AreaEllipse"},
      { -582, "AttemptLockLayerRom"},
      { -264, "AreaEnd"},
      { -252, "AreaMove"},
      { -474, "AskFont"},
      { -84, "AskSoftStyle"},
      { -30, "BltBitMap"},
      { -606, "BltBltMapRastPort"},
      { -300, "BltClear"},
      { -636, "BltMaskBitMapRastPort"},
      { -312, "BltPattern"},
      { -36, "BltTemplate"},
      { -420, "ChangeSprite"},
      { -42, "ClearEOL"},
      { -522, "ClearRectRegion"},
      { -48, "ClearScreen"},
      { -552, "ClipBlit"},
      { -78, "CloseFont"},
      { -372, "CMove"},
      { -450, "CopySBitMap"},
      { -378, "CWait"},
      { -462, "DisownBlitter"},
      { -534, "DisposeRegion"},
      { -108, "DoCollision"},
      { -246, "Draw"},
      { -180, "DrawEllipse"},
      { -330, "Flood"},
      { -576, "FreeColorMap"},
      { -546, "FreeCopList"},
      { -564, "FreeCprList"},
      { -498, "FreeRaster"},
      { -414, "FreeSprite"},
      { -570, "GetColorMap"},
      { -168, "GetGBuffers"},
      { -582, "GetRGB4"},
      { -408, "GetSprite"},
      { -282, "InitArea"},
      { -390, "InitBitMap"},
      { -120, "InitGels"},
      { -174, "InitGMasks"},
      { -126, "InitMasks"},
      { -198, "InitRastPort"},
      { -468, "InitTmpRas"},
      { -360, "InitView"},
      { -204, "InitVPort"},
      { -192, "LoadRGB4"},
      { -222, "LoadView"},
      { -216, "MakeVPort"},
      { -426, "MoveSprite"},
      { -210, "MrgCop"},
      { -516, "NewRegion"},
      { -72, "OpenFont"},
      { -510, "OrRectRegion"},
      { -612, "OrRegionRegion"},
      { -456, "OwnBlitter"},
      { -336, "PolyDraw"},
      { -276, "QBlit"},
      { -294, "QBSlit"},
      { -318, "ReadPixel"},
      { -306, "RectFill"},
      { -486, "RemFont"},
      { -132, "RemIBob"},
      { -396, "ScrollRaster"},
      { -588, "ScrollVPort"},
      { -342, "SetAPen"},
      { -348, "SetBPen"},
      { -144, "SetCollision"},
      { -354, "SetDrMd"},
      { -66, "SetFont"},
      { -234, "SetRast"},
      { -288, "SetRGB4"},
      { -630, "SetRGB4CM"},
      { -90, "SetSoftStyle"},
      { -150, "SortGList"},
      { -60, "Text"},
      { -54, "Textlength"},
      { -438, "UnlockLayerRom"},
      { -384, "VBeamPos"},
      { -228, "WaitBlit"},
      { -402, "WaitBOVP"},
      { -270, "WaitTOF"},
      { -324, "WritePixel"},
      { -558, "XorRectRegion"},
      { -618, "XorRegionRegion"},
      }
   } , 
   {  "icon.library", {
      { -48 , "AddFreeList"},
      { -66 , "AllocWBObject"},
      { -108, "BumpRevision"},
      { -96, "FindToolType"},
      { -90, "FreeDiskObject"},
      { -54, "FreeFreeList"},
      { -60, "FreeWBObject"},
      { -78, "GetDiskObject"},
      { -42, "GetIcon"},
      { -30, "GetWBObject"},
      { -102, "MatchToolValue"},
      { -84, "PutDiskObject"},
      { -48, "PutIcon"},
      { -36, "PutWBObject"},
      }
   } ,
   { "intuition.library", {
      { -462 , "ActivateGadget"},
      { -450 , "ActivateWindow"},
      { -42, "AddGadget"},
      { -438, "AddGList"},
      { -396, "AllocRemember"},
      { -348, "AutoRequest"},
      { -354, "BeginRefresh"},
      { -360, "BuildSysRequest"},
      { -48, "ClearDMRequest"},
      { -54, "ClearMenuStrip"},
      { -60, "ClearPointer"},
      { -66, "CloseScreen"},
      { -72, "CloseWindow"},
      { -78, "CloseWorkBench"},
      { -84, "CurrentTime"},
      { -90, "DisplayAlert"},
      { -96, "DisplayBeep"},
      { -102, "DoubleClick"},
      { -108, "DrawBorder"},
      { -114, "DrawImage"},
      { -366, "EndRefresh"},
      { -120, "EndRequest"},
      { -408, "FreeRemember"},
      { -372, "FreeSysRequest"},
      { -126, "GetDefPrefs"},
      { -132, "GetPrefs"},
      { -426, "GetSereenData"},
      { -138, "InitRequester"},
      { -330, "IntuiTextLength"},
      { -36, "Intuition"},
      { -144, "ItemAddress"},
      { -414, "LockIBase"},
      { -378, "MakeScreen"},
      { -150, "ModifyIDCMP"},
      { -156, "ModifyProp"},
      { -162, "MoveScreen"},
      { -168, "MoveWindow"},
      { -468, "NewModifyProp"},
      { -174, "OffGadget"},
      { -180, "OffMenu"},
      { -186, "OnGadget"},
      { -192, "OnMenu"},
      { -198, "OpenScreen"},
      { -204, "OpenWindow"},
      { -210, "OpenWorkBench"},
      { -216, "PrintIText"},
      { -222, "RefreshGadgets"},
      { -432, "RefreshGList"},
      { -456, "RefreshWindowFrame"},
      { -384, "RemakeDisplay"},
      { -228, "RemoveGadget"},
      { -444, "RemoveGList"},
      { -234, "ReportMouse"},
      { -240, "Request"},
      { -390, "RethinkDisplay"},
      { -246, "ScreenToBack"},
      { -252, "ScreenToFront"},
      { -258, "SetDMRequest"},
      { -264, "SetMenuStrip"},
      { -270, "SetPointer"},
      { -324, "SetPrefs"},
      { -276, "SetWindowTitles"},
      { -282, "ShowTitle"},
      { -288, "SizeWindow"},
      { -420, "UnlockIBase"},
      { -294, "ViewAddress"},
      { -300, "ViewPortAddress"},
      { -336, "WBenchToBack"},
      { -342, "WBenchToFront"},
      { -318, "WindowLimits"},
      { -306, "WindowToBack"},
      { -312, "WindowToFront"},
      }
   },
   { "layers.library", {
      { -78, "BeginUpdate"},
      { -54, "BehindLayer"},
      { -42, "CreateBehindlayer"},
      { -36, "CreateUpfrontLayer"},
      { -90, "DeleteLayer"},
      { -150, "DisposeLayerInfo"},
      { -84, "EndUpdate"},
      { -156, "FattenLayerInfo"},
      { -30, "InitLayers"},
      { -174, "InstallClipRegion"},
      { -96, "LockLayer"},
      { -120, "LockLayerInfo"},
      { -432, "LockLayerRom"},
      { -108, "LockLayers"},
      { -240, "Move"},
      { -60, "MoveLayer"},
      { -168, "MoveLayerInFrontOf"},
      { -144, "NewLayerInfo"},
      { -72, "ScrollLayer"},
      { -66, "SizeLayer"},
      { -126, "SwapBitsRastPortClipRect"},
      { -444, "SyncSBitMap"},
      { -162, "ThinLayerInfo"},
      { -102, "UnlockLayer"},
      { -138, "UnlockLayerInfo"},
      { -114, "UnlockLayers"},
      { -48, "UpFrontLayer"},
      { -132, "WhichLayer"},
      }
   },
};

std::string FunctionHelper::GetFunctionName(std::string lib_name, short index)
{
   if ((library_helper_.find(lib_name) != library_helper_.end()) && (library_helper_[lib_name].find(index) != library_helper_[lib_name].end()))
   {
      return library_helper_[lib_name][index];
      
   }
   else
   {
      if ((library_helper_.find("default") != library_helper_.end()) && (library_helper_["default"].find(index) != library_helper_["default"].end()))
      {
         return library_helper_["default"][index];

      }
      return "";
   }

}